L15HW23 add UserRegistration
vkozlovtech/Kozlov_Java_Basic_05_10_2023 pull request #14
Opened 2023-11-11 15:46 UTC by vkozlovtech

L15HW23 add UserRegistration

2023-11-11 21:30 UTC, JIeIIIa requested changes

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +    private final String confirmPassword;
Який сенс зберігати окремо поле `confirmPassword`? Якщо валідація пройшла успішно і користувача створено (конструктор відпрацював), то дане поле завжди буде дорівнювати `password`. Якщо ж валідація не пройшла, то обʼєкт типу `User` не має бути створено

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        if (isValidLogin(login) == false) {
Порівняння чогось з `true` або  `false` - це ознака "поганого" коду. У нас є логічне заперечення. Тому умову можна переписати
```
if (!isValidLogin(login)) { ... }
```
Але, якщо є тільки один метод, то я б радив перейменувати його і зробити так, щоб в методі перевірялась протилежна умова
```
if (isNotValidLogin(login) {  // повертає true, якщо валідація не пройшла
   ...
}
```

Якщо ж піти далі, то ifʼи тобі насправді не потрібні;) Методи `isValid*` можуть бути `void` і у разі помилки кидати ексепшин.

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        System.out.println("\nRegistration is successful.");
Для тесту - це ок але для бізнес логіки даний вивід зайвий.

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        Pattern p = Pattern.compile(regex);
По-перше що це за імена `p` та `m`? По-друге є сенс зробити патер статичною константою і не створювати кожен раз детальніше див цю відповідь і посилання у ній https://softwareengineering.stackexchange.com/a/216324

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        String regex = "^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]){6,25}$";
Здається знак долара вкінці зайвий. Перевір, будь ласка

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/UserRegistration.java
> +        try {
А навіщо тут try-finally? З методу `registerUser` ніякий exception вилітити не може. Тому якщо try прибрати, то все буде працювати так само

2023-11-11 21:30 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/UserRegistration.java
> +                if (i < 2) {
тут має бути не 2, а звʼязок зі змінною `attemps`. Інакше у 18 рядку змінеш кіл-сть, тут змінити забудеш і отримає багу

2023-11-11 21:30 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        try {
В тестах не має бути ніякої логіки. Якщо ти хочеш перевірити що якийсь код кидає exception, то є 
```
WrongLoginException exception = assertThrows(WrongLoginException.class, () -> new User(login, password, password));
assertEquals("EXPECTED MESSAGE", exception.getMessage()); 
```
Зверни увагу, що я двічі підставив password і так читаючи цей рядок коду, імхо, зрозуміліше що пароль і падтвердження співпадають.
Про `assertThrows` на лекції було. Про те, що даний метод щось повертає я не казав. Вище приклад як можна додатково перевіряти exception, який повертається (робити це чи ні - на твій розсуд)

2023-11-11 21:30 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        String password = "Tester@";
тут краще, щоб пароль відповідав обовʼязковим критеріям (літери + цифри) і містив це спец символ. Зараз не очевидно чому юзер не створюється: немає цифри у паролі чи є заборонений символ. 
І аналогічно до зауваження вище: якщо пароль і підтвердження співпадають, то достатньо однієї змінної

2023-11-11 21:30 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +public class UserTest {
Молодець. Перевірив майже всі випадки. Забув тільки, що кожне з полів може бути `null`. Додай тести для кожного випадку

2023-11-14 15:44 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +    private final String confirmPassword;
Виправив.

2023-11-15 07:13 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +        if (isValidLogin(login) == false) {
Виправив.

2023-11-15 07:13 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +        System.out.println("\nRegistration is successful.");
Виправив.

2023-11-15 07:21 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +        String regex = "^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]){6,25}$";
Хм, на всіх ресурсах які дивився - вказувалось, що на початку і в кінці виразу повинні бути ^ та $ відповідно.. але я їх видалив у себе і тести проходять так само.. дивина. Залишаю тоді вирази без цих символів.

2023-11-15 07:22 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/UserRegistration.java
> +        try {
виправив.

2023-11-15 07:23 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/UserRegistration.java
> +                if (i < 2) {
Точно, елементарна помилка, виправив, дякую.

2023-11-15 07:24 UTC, vkozlovtech commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        try {
Виправив.

2023-11-15 07:24 UTC, vkozlovtech commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        String password = "Tester@";
Виправив.

2023-11-15 07:24 UTC, vkozlovtech commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +public class UserTest {
Додав.

2023-11-15 07:40 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +        Pattern p = Pattern.compile(regex);
Використав такі імена бо вони використовувались у всіх випадках які я шукав, і думав що це стандартні значення типу i, j etc тільки для регулярних виразів. Зробив патерни двома окремими статичними константами класу.

2023-11-15 13:39 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +    private final static String loginRegex = "[a-zA-Z]{1,20}";
Неймінг. для статичних констант тільки SCREAMING_SNAKE_CASE
Також спочатку статичні константи/змінні, а потім поля класу

2023-11-15 13:39 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +    public static void isValidLogin(String login, String loginRegex) throws WrongLoginException {
Передавати loginRegex як параметр в даному випадку немає сенсу. Ти ж завжди використовуєш статичну константу для цього. 
Також метод я б назвав `validateLogin`. Назва, що починається з `is*` передбачає, що метод повертає `boolean` значення (асоціація з геттером для `boolean` змунної)

2023-11-15 13:39 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        Pattern pattern = Pattern.compile(loginRegex);
Я ж не дарма давав посилання... Мабуть, ти не зрозумі зауваження( 
Кожен раз коли ти викливаєш `compile` метод JVM має виконати якісь операції по "налаштуванню" паттерна (не будемо вдаватись в деталі, але операції не зовсім тривіальні). Після налаштуванню обʼєкту типу `Pattern` можна буде передавати рядки для валідації. В твої реалізації налаштовувати патерн потрібно буде кожен раз коли викликається метод.  Натомість, якщо винести 
```
Pattern pattern = Pattern.compile(loginRegex); // назва pattern для статичної константи не підходить
```
у статичну константу, то даний обʼєкт буде створено/ініціалізовано тільки один раз (під час першого звернення до класу). Потім обʼєкт можна використовувати в методах

2023-11-15 13:39 UTC, JIeIIIa commented on src/main/java/ua/vodafone/lecture15/User.java
> +        Pattern p = Pattern.compile(regex);
ти ж не паттерн зробив константою, а рекесп. лишив окремий комент;)

2023-11-15 13:48 UTC, JIeIIIa requested changes

2023-11-15 13:48 UTC, JIeIIIa commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        boolean noThrown;
Ця змінна зайва. Конструкція try-catch в тесті також зайва (не розумію чому ти тут її лишив). 
За замовчуванням JUnit очікує, що з тестового методу не буде "вилітати" exception. Якщо ж таке стається, то тест не пройде. В іншому випадку exception'ів не було і тест буде зеленим. Ти ж, коли використовуєш `Assertions.assertTrue(noThrown);` намагаєшся робити те саме, але явно

2023-11-15 14:11 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +    private final static String loginRegex = "[a-zA-Z]{1,20}";
Точно! Виправив.

2023-11-15 14:12 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +    public static void isValidLogin(String login, String loginRegex) throws WrongLoginException {
виправив

2023-11-15 14:12 UTC, vkozlovtech commented on src/main/java/ua/vodafone/lecture15/User.java
> +        Pattern pattern = Pattern.compile(loginRegex);
Ага, сподіваюсь вірно зрозумів комент, виправив

2023-11-15 14:17 UTC, vkozlovtech commented on src/test/java/ua/vodafone/lecture15/UserTest.java
> +        boolean noThrown;
Видалив try catch, змінну noThrown та Assertions.assertTrue(noThrown), тест дійсно проходить :)

2023-11-15 14:50 UTC, JIeIIIa approved these changes

2023-11-27 07:08 UTC, merged