L7HW11 add MatricesTransposition
vkozlovtech/Kozlov_Java_Basic_05_10_2023 pull request #2
Opened 2023-10-12 05:53 UTC by vkozlovtech

L7HW11 add MatricesTransposition.java

2023-10-12 18:07 UTC, JIeIIIa requested changes

2023-10-12 18:07 UTC, JIeIIIa commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +        int[][] transposedMatrix = new int[matrix[i].length][matrix.length];
не обов'язково було змінну заводити. можна було звернутись до matrix[0]

2023-10-12 18:07 UTC, JIeIIIa commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +        for (i = 0; i < transposedMatrix[i].length; i++) {
Дана умова дещо складна для розуміння. Можеш пояснити словами по чому іде ітерація зовнішнього цикла?
Якож програма падає з помилкою для row=10, column=4

2023-10-14 06:16 UTC, vkozlovtech commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +        int[][] transposedMatrix = new int[matrix[i].length][matrix.length];
точно, дякую!

2023-10-14 06:20 UTC, vkozlovtech commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +        for (i = 0; i < transposedMatrix[i].length; i++) {
Фактично по номеру рядка масива matrix. Зрозумів що дійсно заплутано було це робити через масив transposedMatrix.

2023-10-14 19:03 UTC, JIeIIIa commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +            for (int j = 0; j < matrix[0].length; j++) {
Тут ти перебираєш i-ий рядок. Тож для підкреслення цього факту краще замість `matrix[0]` вказувати `matrix[i]`

2023-10-14 19:03 UTC, JIeIIIa commented on src/ua/vodafone/lecture07/homework/MatricesTransposition.java
> +        for (i = 0; i < transposedMatrix[i].length; i++) {
Насправді якщо ти робив через `transposedMatrix`, то так само потрібно було зовнішній цикл зробити по рядкам транспонованої матриці, а внутрішній по елементам в рядку.

2023-10-14 19:05 UTC, JIeIIIa approved these changes

2023-10-15 15:38 UTC, merged