L9HW15 add FitnessTracker (User)
vkozlovtech/Kozlov_Java_Basic_05_10_2023 pull request #6
Opened 2023-10-19 05:26 UTC by vkozlovtech

L9HW15 add FitnessTracker (User.java)

2023-10-19 08:50 UTC, JIeIIIa requested changes

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String lastName;
Забув про інкапсуляцію

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private String firstName;
Я додаю в клас новий метод:
```
public void foo() {
    firstName = null;
}
```
Все скомпілюється і буде працювати. Виходить поле можна змінювати?!

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String stepsPerDay;
Чому кількість днів зберігається як рядок? Хіба тут може бути щось, крім числа?

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String weight;
Чому вага днів зберігається як рядок? А б очікував тут побачити дійсне число.

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +        System.out.println("User: " + firstName + " " + lastName + ", " + birthDate + ", " + age +
Дивний вивід для людей, які народились з жовтня по грудень. Наприклад, для Ді Капріо

2023-10-19 08:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +        this.age = 2023 - year;
на оцінку не вплинуло, але 2023 можна було б винести як константу - було б зрозуміліше що це за число

2023-10-19 14:07 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String lastName;
Це ти про те, що lastName - stepsPerDay не мають модифікатору private?

2023-10-19 14:29 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private String firstName;
ага, дійсно, додав final

2023-10-19 14:29 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String weight;
згоден, змінив на double

2023-10-19 14:29 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    String stepsPerDay;
згоден, змінив на int

2023-10-19 14:30 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +        this.age = 2023 - year;
зробив константу CURRENT_YEAR

2023-10-19 14:31 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +        System.out.println("User: " + firstName + " " + lastName + ", " + birthDate + ", " + age +
Додав метод makeBirthDate()

2023-10-19 21:50 UTC, JIeIIIa requested changes

2023-10-19 21:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private String makeBirthDate(int day, int month, int year) {
На скільки я зрозумів, то метод працює не так, як ти задумав. Для 1, 1, 2001 буде виведено 01.1.2001 замість 01.01.2001

2023-10-19 21:50 UTC, JIeIIIa commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private static final int CURRENT_YEAR = 2023;
Я казав, що спочатку статичні константи, статичні змінні, потім поля класи, далі конструктори, гетери/сетери і після цього решта методів. Давай дотримуватись такої структури;)

2023-10-22 11:28 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private String makeBirthDate(int day, int month, int year) {
Виправив.

2023-10-22 11:28 UTC, vkozlovtech commented on src/ua/vodafone/lecture09/fitnessTracker/User.java
> +    private static final int CURRENT_YEAR = 2023;
Майже так все і було, буду слідкувати уважніше) виправив

2023-10-24 11:36 UTC, merged