L10HW16 add Point
vkozlovtech/Kozlov_Java_Basic_05_10_2023 pull request #7
Opened 2023-10-25 05:44 UTC by vkozlovtech

L10HW16 add Point.java and PointRunner.java

2023-10-25 14:53 UTC, JIeIIIa requested changes

2023-10-25 14:53 UTC, JIeIIIa commented on src/ua/vodafone/lecture10/Point.java
> +        if (otherPoint != null) {
Не помилка, але краще уникати заперечень в умовах. В даному випадку
```
if (otherPoint == null) {
    return -1;
}
return calculateDistanceBetweenTwo(this, otherPoint);
```
А якщо піти ще далі, то достатньо буде зробити тільки
```
return calculateDistanceBetweenTwo(this, otherPoint);
```
Тому що у наступному методі є перевірка на `null` для другого параметра ;)

2023-10-25 14:53 UTC, JIeIIIa commented on src/ua/vodafone/lecture10/Point.java
> +        if (firstPoint != null && secondPoint != null) {
Аналогічно
```
if (firstPoint == null || secondPoint == null) {
    return -1;
}
return Math.sqrt(Math.pow((secondPoint.x - firstPoint.x), 2) + Math.pow((secondPoint.y - firstPoint.y), 2));
```

2023-10-25 14:53 UTC, JIeIIIa commented on src/ua/vodafone/lecture10/Point.java
> +    public static String comparePoints(Point firstPoint, Point secondPoint) {
Сам собі зробив гірше: цей метод за умовою не вимагався. Але якщо ти робиш утілітний метод, то він теж може приймати `null` як параметри

2023-10-25 14:53 UTC, JIeIIIa commented on src/ua/vodafone/lecture10/Point.java
> +    public static Point clone(Point point) {
Параметр може бути `null`
Не бачу перевизначеного методу `clone()` з класу `Object`

2023-10-25 14:53 UTC, JIeIIIa commented on src/ua/vodafone/lecture10/PointRunner.java
> +        System.out.println("\n-= Copy first point via constructor =-\n" +
Коли робиш копії, то бажано виводити порівняння через `equals` та `==` щоб було видно, що обʼєкт в памʼяті різні, але значення в них однакове

2023-10-27 06:29 UTC, vkozlovtech commented on src/ua/vodafone/lecture10/Point.java
> +        if (otherPoint != null) {
Виправив.

2023-10-27 06:29 UTC, vkozlovtech commented on src/ua/vodafone/lecture10/Point.java
> +        if (firstPoint != null && secondPoint != null) {
Виправив.

2023-10-27 06:30 UTC, vkozlovtech commented on src/ua/vodafone/lecture10/Point.java
> +    public static Point clone(Point point) {
Виправив.

2023-10-27 06:36 UTC, vkozlovtech commented on src/ua/vodafone/lecture10/Point.java
> +    public static String comparePoints(Point firstPoint, Point secondPoint) {
Видалив утілітний метод, використав для порівняння тільки equals()

2023-10-27 06:55 UTC, vkozlovtech commented on src/ua/vodafone/lecture10/PointRunner.java
> +        System.out.println("\n-= Copy first point via constructor =-\n" +
Додав порівняння.

2023-10-27 07:09 UTC, JIeIIIa approved these changes

2023-10-27 07:24 UTC, merged