L12HW19 add Interfaces
vkozlovtech/Kozlov_Java_Basic_05_10_2023 pull request #9
Opened 2023-10-28 14:43 UTC by vkozlovtech

L12HW19 add Interfaces

2023-10-28 15:38 UTC, JIeIIIa requested changes

2023-10-28 15:38 UTC, JIeIIIa commented on src/ua/vodafone/lecture12/Smartphones.java
> +    public void sms(String text);
А для відправки смс номер не потрібен?:D

2023-10-28 15:38 UTC, JIeIIIa commented on src/ua/vodafone/lecture12/smartphonesRunner.java
> +public class smartphonesRunner {
Назви класів мають бути з великої літери

2023-10-28 15:38 UTC, JIeIIIa commented on src/ua/vodafone/lecture12/Android.java
> +        }   else {
Форматуування коду

2023-10-28 15:38 UTC, JIeIIIa commented on src/ua/vodafone/lecture12/Iphone.java
> +        }   else {
форматування коду

2023-10-28 15:38 UTC, JIeIIIa commented on src/ua/vodafone/lecture12/smartphonesRunner.java
> +
Щоб закріпити матеріал, додай ще цикл for each, який зробить щось з усіма `smartphones`

2023-10-29 11:36 UTC, vkozlovtech commented on src/ua/vodafone/lecture12/Iphone.java
> +        }   else {
Виправив.

2023-10-29 11:37 UTC, vkozlovtech commented on src/ua/vodafone/lecture12/Android.java
> +        }   else {
Виправив.

2023-10-29 11:37 UTC, vkozlovtech commented on src/ua/vodafone/lecture12/Smartphones.java
> +    public void sms(String text);
Ага, блін як працівнику водафон аж соромно)) додав

2023-10-29 11:38 UTC, vkozlovtech commented on src/ua/vodafone/lecture12/smartphonesRunner.java
> +public class smartphonesRunner {
виправив.

2023-10-29 21:44 UTC, JIeIIIa approved these changes

2023-10-30 06:58 UTC, merged